package com.samset.recyclerviewsample;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import com.samset.recyclerviewsample.adapter.RecyclerAdapter;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    private RecyclerView recyclerView;
    private LinearLayoutManager layoutManager;
    private RecyclerAdapter adapter;
    private List<String> myData;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        recyclerView= (RecyclerView) findViewById(R.id.recycle);
           setRecyclerView();
    }

    private void setRecyclerView() {
        recyclerView.setHasFixedSize(true);
        layoutManager = new LinearLayoutManager(this);
        layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(layoutManager);
        adapter = new RecyclerAdapter(this, getList());
        recyclerView.setAdapter(adapter);
        adapter.notifyDataSetChanged();
    }
   private List<String> getList()
   {
       List<String> data=new ArrayList<>();
       data.add("USA");
       data.add("India");
       data.add("Canada");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Hungary");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");
       data.add("India");
       data.add("Belgium");
       data.add("India");
       data.add("India");
       data.add("India");
       data.add("Russia");
       data.add("India");
       data.add("India");
       data.add("Afgahnistan");
       data.add("India");
       data.add("Denmark");
       data.add("India");
       data.add("Shri Lanka");
       data.add("India");
       data.add("Pakistan");

       return data;


   }
}
